# Generated by Django 5.0.4 on 2024-04-08 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barkyapi', '0002_alter_bookmark_date_added_alter_bookmark_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='date_added',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='notes',
            field=models.TextField(),
        ),
    ]
